<?php

namespace Database\Seeders;

use App\Models\HelpdeskCase;
use Carbon\Carbon;
use Illuminate\Database\Seeder;

class HelpdeskCaseSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        HelpdeskCase::truncate();

        $cases = [
            [
                'ticket_no' => 'ITD-2026-001',
                'title' => 'คอมพิวเตอร์เปิดไม่ติด จอดำ มีเสียงติ๊ด 3 ครั้ง',
                'description' => 'กดปุ่ม Power แล้วพัดลมหมุน แต่หน้าจอมืดสนิท มีเสียง Beep 3 สั้น จำเป็นต้องใช้งานระบบบัญชีเพื่อปิดงวดประจำเดือนอย่างเร่งด่วน',
                'category' => 'Hardware',
                'priority' => 'urgent',
                'status' => 'pending',
                'requester_name' => 'วรัญญา เมธาวี',
                'requester_email' => 'waranya.m@company.co.th',
                'requester_phone' => '02-555-1234 ต่อ 102',
                'department' => 'ฝ่ายการเงินและบัญชี',
                'location' => 'อาคาร 1 ชั้น 4 โต๊ะ ACC-08',
                'assigned_to' => null,
                'resolution_notes' => null,
                'sla_due_at' => Carbon::now()->addHours(1),
                'resolved_at' => null,
                'created_at' => Carbon::now()->subMinutes(35),
            ],
            [
                'ticket_no' => 'ITD-2026-002',
                'title' => 'เครื่องพิมพ์ Brother ชั้น 3 ปริ้นไม่ออก ไฟแดงกระพริบกระดาษติด',
                'description' => 'ส่งงานพิมพ์เอกสารสัญญาแล้วเครื่องไม่ดึงกระดาษ มีไฟสัญลักษณ์กระดาษติดกระพริบ ลองเปิดฝาดูแล้วไม่พบเศษกระดาษตกค้าง',
                'category' => 'Printer & Peripherals',
                'priority' => 'high',
                'status' => 'pending',
                'requester_name' => 'ธีรภัทร ชาญวิทย์',
                'requester_email' => 'theerapat.c@company.co.th',
                'requester_phone' => '081-999-8877',
                'department' => 'ฝ่ายทรัพยากรบุคคล (HR)',
                'location' => 'อาคาร 2 ชั้น 3 โถงกลาง',
                'assigned_to' => null,
                'resolution_notes' => null,
                'sla_due_at' => Carbon::now()->addHours(2),
                'resolved_at' => null,
                'created_at' => Carbon::now()->subHours(1)->subMinutes(15),
            ],
            [
                'ticket_no' => 'ITD-2026-003',
                'title' => 'ขอสิทธิ์เข้าใช้งานระบบ ERP โมดูลจัดซื้อสำหรับพนักงานใหม่',
                'description' => 'พนักงานใหม่เริ่มงานวันแรก รหัสพนักงาน EMP-69022 ขอเพิ่มสิทธิ์ Role: Buyer ในระบบ SAP/ERP และขอตั้งค่าอีเมลองค์กร',
                'category' => 'Access & Account',
                'priority' => 'medium',
                'status' => 'pending',
                'requester_name' => 'ธนกร เจริญสุข',
                'requester_email' => 'thanakorn.j@company.co.th',
                'requester_phone' => '02-555-1234 ต่อ 205',
                'department' => 'ฝ่ายจัดซื้อและพัสดุ',
                'location' => 'อาคาร 1 ชั้น 2 แผนกจัดซื้อ',
                'assigned_to' => null,
                'resolution_notes' => null,
                'sla_due_at' => Carbon::now()->addHours(4),
                'resolved_at' => null,
                'created_at' => Carbon::now()->subHours(2),
            ],
            [
                'ticket_no' => 'ITD-2026-004',
                'title' => 'สัญญาณ Wi-Fi หลุดบ่อยในห้องประชุมใหญ่ A2 มีประชุมผู้บริหาร',
                'description' => 'อุปกรณ์เชื่อมต่อ SSID "Corp-Staff" แล้วหลุดทุกๆ 5 นาที ขณะนี้กำลังมีการประชุมทางไกลผ่าน Zoom ขอให้ทีมเน็ตเวิร์กช่วยเช็ค Access Point ด่วน',
                'category' => 'Network',
                'priority' => 'urgent',
                'status' => 'pending',
                'requester_name' => 'ภานุมาศ รัตนกุล',
                'requester_email' => 'panumat.r@company.co.th',
                'requester_phone' => '089-123-4567',
                'department' => 'ฝ่ายการตลาดและสื่อสารองค์กร',
                'location' => 'อาคาร 1 ชั้น 5 ห้องประชุม A2',
                'assigned_to' => null,
                'resolution_notes' => null,
                'sla_due_at' => Carbon::now()->addMinutes(45),
                'resolved_at' => null,
                'created_at' => Carbon::now()->subMinutes(15),
            ],
            [
                'ticket_no' => 'ITD-2026-005',
                'title' => 'โปรแกรม Microsoft Outlook เปิดไม่ขึ้น แสดง Error 0x8004010F',
                'description' => 'ไม่สามารถส่งอีเมลเสนอราคาให้ลูกค้าได้ Outlook แจ้งว่า data file (.ost) มีปัญหาและสั่งปิดโปรแกรมอัตโนมัติ',
                'category' => 'Software',
                'priority' => 'high',
                'status' => 'pending',
                'requester_name' => 'รัชดาพร วงศ์สว่าง',
                'requester_email' => 'ratchadaporn.w@company.co.th',
                'requester_phone' => '02-555-1234 ต่อ 312',
                'department' => 'ฝ่ายขายในประเทศ',
                'location' => 'อาคาร 2 ชั้น 4 โซน Sales',
                'assigned_to' => null,
                'resolution_notes' => null,
                'sla_due_at' => Carbon::now()->addHours(3),
                'resolved_at' => null,
                'created_at' => Carbon::now()->subHours(3),
            ],
            [
                'ticket_no' => 'ITD-2026-006',
                'title' => 'สาย LAN ขาด/หัว RJ-45 แตก บริเวณโต๊ะทำงานที่ 14',
                'description' => 'เก้าอี้ล้อเลื่อนทับสายแลนทำให้เขี้ยวล็อคหัวต่อหักและสายขาดใน ทำให้คอมพิวเตอร์ไม่สามารถเชื่อมต่อระบบเครือข่ายภายในได้',
                'category' => 'Network',
                'priority' => 'medium',
                'status' => 'pending',
                'requester_name' => 'กฤษณะ อินทร์พรหม',
                'requester_email' => 'kritsana.i@company.co.th',
                'requester_phone' => '084-555-6677',
                'department' => 'ฝ่ายปฏิบัติการ',
                'location' => 'อาคาร 3 ชั้น 1 โต๊ะ OP-14',
                'assigned_to' => null,
                'resolution_notes' => null,
                'sla_due_at' => Carbon::now()->subHours(1),
                'resolved_at' => null, // Hardware Specialist
                'created_at' => Carbon::now()->subHours(4),
            ],
            [
                'ticket_no' => 'ITD-2026-007',
                'title' => 'จอภาพกระพริบเป็นเส้นแนวนอนสีเขียว ทำงานกราฟิกไม่ได้',
                'description' => 'จอ Dell 27 นิ้ว กระพริบเป็นระยะ สลับกับมีเส้นสีเขียวคาด ลองขยับสาย HDMI แล้วยังเป็นเหมือนเดิม รบกวนนำจอสำรองมาเปลี่ยนให้ด้วยครับ',
                'category' => 'Hardware',
                'priority' => 'high',
                'status' => 'pending',
                'requester_name' => 'ปรียา สุทธิรักษ์',
                'requester_email' => 'preeya.s@company.co.th',
                'requester_phone' => '02-555-1234 ต่อ 408',
                'department' => 'ฝ่ายสื่อสารองค์กรและดีไซน์',
                'location' => 'อาคาร 1 ชั้น 3 ห้อง Creative Studio',
                'assigned_to' => null,
                'resolution_notes' => null,
                'sla_due_at' => Carbon::now()->addHours(2),
                'resolved_at' => null,
                'created_at' => Carbon::now()->subMinutes(50),
            ],
            [
                'ticket_no' => 'ITD-2026-008',
                'title' => 'ขอติดตั้งโปรแกรม AutoCAD 2026 สำหรับเครื่อง Workstation แผนกออกแบบ',
                'description' => 'ได้รับอนุมัติ License จากผู้บริหารแล้ว เอกสารแนบผ่านระบบ e-Document เลขที่ ED-69-102 ขอให้ไอทีลงโปรแกรมและ Activate สิทธิ์',
                'category' => 'Software',
                'priority' => 'low',
                'status' => 'pending',
                'requester_name' => 'พิทยา ศรีวิลัย',
                'requester_email' => 'pittaya.s@company.co.th',
                'requester_phone' => '02-555-1234 ต่อ 511',
                'department' => 'ฝ่ายวิศวกรรมและการออกแบบ',
                'location' => 'อาคาร 3 ชั้น 2 ห้อง Engineering',
                'assigned_to' => null,
                'resolution_notes' => null,
                'sla_due_at' => Carbon::now()->addDay(),
                'resolved_at' => null, // General User
                'created_at' => Carbon::now()->subHours(6),
            ],
            [
                'ticket_no' => 'ITD-2026-009',
                'title' => 'ลืมรหัสผ่านบัญชี Windows Active Directory ต้องการปลดล็อค',
                'description' => 'ใส่รหัสผ่านผิดเกิน 5 ครั้ง ระบบทำการล็อคบัญชี ไม่สามารถเข้าใช้งานเครื่องเพื่อสแกนรับสินค้าเข้าคลังได้',
                'category' => 'Access & Account',
                'priority' => 'urgent',
                'status' => 'pending',
                'requester_name' => 'นเรศ ปัญญาวงศ์',
                'requester_email' => 'nares.p@company.co.th',
                'requester_phone' => '086-777-3322',
                'department' => 'ฝ่ายคลังสินค้าและโลจิสติกส์',
                'location' => 'คลังสินค้าหลัก ท่าเรือ 2',
                'assigned_to' => null,
                'resolution_notes' => null,
                'sla_due_at' => Carbon::now()->subHours(2),
                'resolved_at' => null,
                'created_at' => Carbon::now()->subHours(3),
            ],
            [
                'ticket_no' => 'ITD-2026-010',
                'title' => 'เครื่องสแกนบาร์โค้ดไร้สายยิงไม่ติด ไม่ส่งข้อมูลเข้าหน้าจอ POS',
                'description' => 'เครื่องสแกนบาร์โค้ดไร้สาย (Datalogic) มีไฟขึ้นปกติแต่เมื่อยิงแล้วไม่มีเสียง Beep และตัวเลขไม่ปรากฏในระบบขายหน้าร้าน',
                'category' => 'Hardware',
                'priority' => 'medium',
                'status' => 'pending',
                'requester_name' => 'สุพจน์ มั่นคง',
                'requester_email' => 'supot.m@company.co.th',
                'requester_phone' => '082-333-4411',
                'department' => 'ฝ่ายคลังสินค้าและโลจิสติกส์',
                'location' => 'ศูนย์กระจายสินค้า จุดแพ็คที่ 3',
                'assigned_to' => null,
                'resolution_notes' => null,
                'sla_due_at' => Carbon::now()->addHours(3),
                'resolved_at' => null,
                'created_at' => Carbon::now()->subMinutes(25),
            ],
            [
                'ticket_no' => 'ITD-2026-011',
                'title' => 'ขอเพิ่มพื้นที่ Google Drive / OneDrive สำหรับจัดเก็บไฟล์โปรเจกต์',
                'description' => 'พื้นที่เก็บข้อมูลใน OneDrive เต็ม 100 GB ไม่สามารถ Sync เอกสารนำเสนอขนาดใหญ่ได้ ต้องการขออัปเกรดเป็น 1 TB',
                'category' => 'Access & Account',
                'priority' => 'low',
                'status' => 'pending',
                'requester_name' => 'มินตรา วัฒนากุล',
                'requester_email' => 'mintra.w@company.co.th',
                'requester_phone' => '02-555-1234 ต่อ 118',
                'department' => 'ฝ่ายพัฒนาธุรกิจ',
                'location' => 'อาคาร 1 ชั้น 4 โซน BD',
                'assigned_to' => null,
                'resolution_notes' => null,
                'sla_due_at' => Carbon::now()->addHours(6),
                'resolved_at' => null,
                'created_at' => Carbon::now()->subHours(2)->subMinutes(40),
            ],
            [
                'ticket_no' => 'ITD-2026-012',
                'title' => 'เมาส์ไร้สายและคีย์บอร์ดเชื่อมต่อไม่ได้ เปลี่ยนถ่านแล้วยังไม่หาย',
                'description' => 'USB Wireless Dongle อาจจะชำรุด เสียบแล้ว Windows ฟ้อง Device not recognized ลองเปลี่ยนพอร์ตแล้วยังไม่พบอุปกรณ์',
                'category' => 'Hardware',
                'priority' => 'low',
                'status' => 'pending',
                'requester_name' => 'สุภาพร แดงสุวรรณ',
                'requester_email' => 'supaporn.d@company.co.th',
                'requester_phone' => '02-555-1234 ต่อ 101',
                'department' => 'ฝ่ายธุรการและอำนวยการ',
                'location' => 'อาคาร 1 ชั้น 1 ห้องประชาสัมพันธ์',
                'assigned_to' => null,
                'resolution_notes' => null,
                'sla_due_at' => Carbon::now()->subHours(3),
                'resolved_at' => null,
                'created_at' => Carbon::now()->subHours(5),
            ],
        ];

        foreach ($cases as $item) {
            HelpdeskCase::create($item);
        }
    }
}
